CREATE SCHEMA SGA;

USE SGA;

CREATE TABLE tablasql(
index_sql INT NOT NULL AUTO_INCREMENT,
q10_part_1 LONGTEXT,
q10_part_2 LONGTEXT,
q10_part_3 LONGTEXT,
q10_part_4 LONGTEXT,
q10_part_5 LONGTEXT,
q10_part_6 LONGTEXT,
q10_part_7 LONGTEXT,
q10_part_8 LONGTEXT,
q10_part_9 LONGTEXT,
q10_part_10 LONGTEXT,
q10_part_11 LONGTEXT,
q10_part_12 LONGTEXT,
q10_part_13 LONGTEXT,
q10_part_14 LONGTEXT,
q10_part_15 LONGTEXT,
q10_part_16 LONGTEXT,
q10_other LONGTEXT,
d482xta LONGTEXT,
PRIMARY KEY (index_sql));

CREATE TABLE tablaxml(
index_xml INT NOT NULL AUTO_INCREMENT,
time LONGTEXT,
age LONGTEXT,
gender LONGTEXT,
index_sql INT,
PRIMARY KEY (index_xml),
CONSTRAINT `fk_tablasql_tablaxml`
FOREIGN KEY (index_sql)
REFERENCES tablasql (index_sql));

CREATE TABLE tablatxt(
index_txt INT NOT NULL AUTO_INCREMENT,
index_sql INT, 
q3 LONGTEXT,
q4 LONGTEXT,
q5 LONGTEXT,
q6 LONGTEXT,
q7 LONGTEXT,
q8 LONGTEXT,
q9 LONGTEXT,
q11 LONGTEXT,
q12 LONGTEXT,
q13 LONGTEXT,
q14 LONGTEXT,
q15 LONGTEXT,
q16 LONGTEXT,
q17 LONGTEXT,
q20 LONGTEXT,
q21 LONGTEXT,
q22 LONGTEXT,
q23 LONGTEXT,
q24 LONGTEXT,
q25 LONGTEXT,
q26 LONGTEXT,
q32 LONGTEXT,
q33 LONGTEXT,
q34 LONGTEXT,
q35 LONGTEXT,
q41 LONGTEXT,
PRIMARY KEY (index_txt),
CONSTRAINT `fk_tablasql_tablatxt` 
FOREIGN KEY (index_sql)
REFERENCES tablasql (index_sql));

USE SGA;

RENAME TABLE tablasql TO data_sql;

RENAME TABLE tablatxt TO data_txt;

RENAME TABLE tablaxml TO data_xml;
